name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  azureCognitiveSubscriptionKey:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  azureCognitiveEndpoint:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  categories:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  labelText:
    required: false
    description: 'input description here'
outputs:
  results:
      description: 'the pii detection results'
runs:
  using: 'node12'
  main: 'dist/index.js'
